# Generated by Django 3.1.7 on 2022-02-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Omote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('age', models.IntegerField(verbose_name='年齢')),
            ],
        ),
        migrations.CreateModel(
            name='Ura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20, verbose_name='クラブ')),
                ('name2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plac3.omote', verbose_name='名前')),
            ],
        ),
    ]
