# Generated by Django 3.1.7 on 2022-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plac5', '0002_auto_20220217_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.IntegerField(verbose_name='認証番号')),
                ('busho', models.CharField(max_length=10, verbose_name='部署')),
                ('name', models.CharField(max_length=10, verbose_name='担当')),
                ('send_name', models.CharField(max_length=10, verbose_name='送付先')),
                ('send_tel', models.CharField(max_length=10, verbose_name='送付先電話')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='sample_number',
            field=models.IntegerField(default=1, verbose_name='認証番号'),
            preserve_default=False,
        ),
    ]
