# Generated by Django 3.1.7 on 2022-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plac5', '0004_auto_20220219_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='color',
            field=models.CharField(max_length=10, verbose_name='カラー'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='size',
            field=models.CharField(max_length=5, verbose_name='サイズ'),
        ),
    ]
