# Generated by Django 3.1.7 on 2022-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plac5', '0006_auto_20220220_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shozoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='担当')),
                ('busho', models.CharField(max_length=10, verbose_name='部署')),
            ],
        ),
    ]
