# Generated by Django 3.1.7 on 2022-02-21 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plac5', '0007_shozoku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plac5.send', verbose_name='認証番号'),
        ),
    ]
