# Generated by Django 3.1.7 on 2022-02-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plac4', '0002_photo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
