# Generated by Django 3.1.7 on 2022-07-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plac9', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='banchi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='番地'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bikou',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='build',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='建物'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='busho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='com',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='顧客ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dm_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='DM'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FAX'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gaisho_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='外商'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kensu',
            field=models.IntegerField(blank=True, null=True, verbose_name='件数'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メール1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メール2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メール3'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mei',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mei_kana',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='名かな'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mob',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='携帯'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='money',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pref',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sei',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sei_kana',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='姓かな'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tantou',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='担当'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TEL'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='toroku',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='yubin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_rec_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plac9.recieve', verbose_name='見積ID'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='eigyou_busho',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='営業部署'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='eigyou_mei',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='担当_名'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='eigyou_sei',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='担当_姓'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='keiro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='流入経路'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='mitsu_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='見積日'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='mitsu_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='見積金額'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_cus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plac9.customer', verbose_name='顧客ID'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='受注日'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='見積ID'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='見積番号'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_ver',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='バージョン'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ステータス'),
        ),
    ]
