# Generated by Django 3.1.7 on 2022-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plac9', '0002_auto_20220702_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住所'),
        ),
    ]
