# Generated by Django 3.1.7 on 2022-07-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plac9', '0003_customer_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tantou',
            field=models.CharField(blank=True, choices=[('井上', '井上'), ('古川', '古川'), ('眞下', '眞下')], max_length=10, null=True, verbose_name='担当'),
        ),
    ]
