# Generated by Django 3.1.7 on 2022-06-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=10, verbose_name='顧客ID')),
                ('sei', models.CharField(max_length=10, null=True, verbose_name='姓')),
                ('mei', models.CharField(max_length=10, null=True, verbose_name='名')),
                ('sei_kana', models.CharField(max_length=10, null=True, verbose_name='姓かな')),
                ('mei_kana', models.CharField(max_length=10, null=True, verbose_name='名かな')),
                ('mail1', models.EmailField(max_length=254, null=True, verbose_name='メール1')),
                ('mail2', models.EmailField(max_length=254, null=True, verbose_name='メール2')),
                ('mail3', models.EmailField(max_length=254, null=True, verbose_name='メール3')),
                ('yubin', models.CharField(max_length=10, null=True, verbose_name='郵便番号')),
                ('pref', models.CharField(max_length=10, null=True, verbose_name='都道府県')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='市区町村')),
                ('banchi', models.CharField(max_length=50, null=True, verbose_name='番地')),
                ('build', models.CharField(max_length=50, null=True, verbose_name='建物')),
                ('com', models.CharField(max_length=50, null=True, verbose_name='会社')),
                ('busho', models.CharField(max_length=50, null=True, verbose_name='部署')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='電話')),
                ('mob', models.CharField(max_length=20, null=True, verbose_name='携帯')),
                ('fax', models.CharField(max_length=20, null=True, verbose_name='FAX')),
                ('toroku', models.CharField(max_length=10, null=True, verbose_name='登録日')),
                ('kensu', models.IntegerField(null=True, verbose_name='件数')),
                ('money', models.IntegerField(null=True, verbose_name='金額')),
                ('tantou', models.CharField(max_length=10, null=True, verbose_name='担当')),
                ('check_dm', models.BooleanField(default=False, verbose_name='DM')),
                ('check_tel', models.BooleanField(default=False, verbose_name='TEL')),
                ('check_gaisho', models.BooleanField(default=False, verbose_name='外商')),
                ('bikou', models.TextField(verbose_name='備考')),
            ],
        ),
    ]
