# Generated by Django 3.1.7 on 2022-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plac8', '0005_auto_20220629_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_rec_id', models.CharField(max_length=10, verbose_name='見積ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='品名')),
            ],
        ),
    ]
