# Generated by Django 3.1.7 on 2022-06-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plac8', '0006_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieve',
            name='eigyou_mei',
            field=models.CharField(max_length=10, null=True, verbose_name='担当_名'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='eigyou_sei',
            field=models.CharField(max_length=10, null=True, verbose_name='担当_姓'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_day',
            field=models.CharField(max_length=10, null=True, verbose_name='受注日'),
        ),
    ]
