# Generated by Django 3.1.7 on 2022-06-30 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plac8', '0007_auto_20220629_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_id',
            field=models.CharField(max_length=10, null=True, verbose_name='顧客ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_rec_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plac8.recieve', verbose_name='見積ID'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_cus_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plac8.customer', verbose_name='顧客ID'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_id',
            field=models.CharField(max_length=10, null=True, verbose_name='見積ID'),
        ),
    ]
