# Generated by Django 3.1.7 on 2022-06-30 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plac8', '0010_auto_20220630_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_rec_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plac8.recieve', verbose_name='見積ID'),
        ),
        migrations.AlterField(
            model_name='recieve',
            name='rec_cus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plac8.customer', verbose_name='顧客ID'),
        ),
    ]
