# Generated by Django 3.1.7 on 2022-02-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinban', models.CharField(max_length=10, verbose_name='品番')),
                ('zaiko', models.IntegerField(verbose_name='在庫')),
                ('category', models.CharField(choices=[('本社', '本社'), ('物流', '物流')], max_length=10, verbose_name='カテゴリ')),
                ('memo', models.TextField(blank=True)),
                ('toroku', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('koshin', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
