# Generated by Django 3.1.7 on 2022-03-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plac7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.CharField(max_length=20)),
                ('hinban', models.CharField(max_length=10)),
                ('kataban', models.CharField(choices=[('1', '01'), ('2', '02'), ('3', '03')], max_length=5)),
            ],
        ),
    ]
